#!/usr/bin/with-contenv bash
# shellcheck shell=bash

echo "**** update system ****" &&
  apk --quiet --no-cache --no-progress update
echo "**** install build packages ****" &&
  apk add --quiet --no-cache --no-progress \
    unzip bc jq findutils fortify-headers linux-headers gcc python3-dev git nano net-tools sudo wget py3-pip libc-dev
echo "**** install pip packages ****" &&
  pip3 install -U \
    requests psutil tabulate requests attrdict PlexAPI
rm -rf /var/cache/apk/*
